Repository jupyterhub/nbgitpuller, pull requests merged in 2024-03, with the labels that each got.

#345 Add test for Python 3.12, jupyter_server 1, notebook 5 and 7, and git 2.43 (ubuntu 24.04)
  .github/workflows/test.yml
  dev-requirements.txt
  pyproject.toml
  tests/test_api.py
Labels: maintenance

#347 403 on failed auth for EventStream
  nbgitpuller/handlers.py
  tests/test_api.py
Labels: enhancement

#346 include xsrf token in event stream request
  nbgitpuller/static/js/gitsync.js
  nbgitpuller/static/js/index.js
  nbgitpuller/templates/status.html
Labels: bug

#348 Add changelog for 1.2.1
  CHANGELOG.md
Labels: documentation
